version: "3"

services:
  db:
    image: nouchka/sqlite3
    environment:
      - DB_NAME=testemed
    volumes:
      - ./src/database:/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=./src/database/database.sqlite
      - ACCESS_TOKENS_STORAGE=sqlite
      - REFRESH_TOKENS_STORAGE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
