version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./src/database:/app/src/database/ # não precisa por todo o código estar do lado de fora
    # depends_on:
    #   - redis
    environment:
      - DB_HOST=./src/database/database.sqlite
      - ACCESS_TOKENS_STORAGE=sqlite
      - REFRESH_TOKENS_STORAGE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=3000
      - SECRET=qualquercoisa
      - SECRET_KEY=senha32bits

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
